services:
  postgres:
    container_name: news-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5433:5432"

  liquibase-migrations:
    container_name: news-migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgres
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/news
      - --username=postgres
      - --password=password
      - update
    volumes:
      - ./migrations:/changesets

volumes:
  postgres-data: